variables:
    LEKT_PLUGIN: mfe
    LEKT_IMAGES: mfe account-dev course-authoring-dev discussions-dev authn-dev gradebook-dev learning-dev profile-dev
    LEKT_PYPI_PACKAGE: lekt-mfe
    OPENEDX_RELEASE: olive
    GITHUB_REPO: lektorium-tutor/lekt-mfe

include:
  - project: 'community/lekt-ci'
    file: 'plugin-gitlab-ci.yml'
